CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS focus_sessions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(100),
  duration INTEGER NOT NULL,
  keypress_count INTEGER DEFAULT 0,
  click_count INTEGER DEFAULT 0,
  tab_hidden_count INTEGER DEFAULT 0,
  focus_score INTEGER DEFAULT 0,
  memo TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (name)
VALUES ('Demo User')
ON CONFLICT DO NOTHING;
