name: FocusGuard CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Install Backend
        working-directory: ./backend
        run: npm install

      - name: Validate Backend
        working-directory: ./backend
        run: node -c server.js

      - name: Docker Compose Build
        run: docker compose build
